# file: roles/minecraft_server_install/tasks/main.yml
---
- name: Creating minecraft group
  group:
    name: 'minecraft'
    state: present

- name: Creating minecraft user with /opt/minecraft home directory
  user:
    name: 'minecraft'
    comment: 'Minecraft Account'
    group: 'minecraft'
    home: '/opt/minecraft'
    state: 'present'

- name: Downloading minecraft server jar file
  get_url:
    url: 'https://launcher.mojang.com/v1/objects/bb2b6b1aefcd70dfd1892149ac3a215f6c636b07/server.jar'
    dest: '/opt/minecraft'
    owner: 'minecraft'
    group: 'minecraft'
    mode: 0644

- name: Creating /opt/minecraft/eula.txt
  copy:
    src: 'eula.txt'
    dest: '/opt/minecraft/eula.txt'
    owner: 'minecraft'
    group: 'minecraft'
    mode: 0644
  
- name: Creating /opt/minecraft/server.properties
  copy:
    src: 'server.properties'
    dest: '/opt/minecraft/server.properties'
    owner: 'minecraft'
    group: 'minecraft'
    mode: 0644
...
