# file: roles/minecraft_server_install/tasks/main.yml
---
- name: Create minecraft group
  group:
    name: 'minecraft'
    state: present

- name: Create minecraft user with /opt/minecraft home directory
  user:
    name: 'minecraft'
    comment: 'Minecraft Account'
    group: 'minecraft'
    home: '/opt/minecraft'
    state: 'present'

- name: Download minecraft server jar file
  get_url:
    url: 'https://launcher.mojang.com/v1/objects/3737db93722a9e39eeada7c27e7aca28b144ffa7/server.jar'
    dest: '/opt/minecraft'
    owner: 'minecraft'
    group: 'minecraft'
    mode: 0644

- name: Copy eula.txt with eula set to true
  copy:
    src: 'eula.txt'
    dest: '/opt/minecraft/eula.txt'
    owner: 'minecraft'
    group: 'minecraft'
    mode: 0644
  
- name: Copy server.properties file
  copy:
    src: 'server.properties'
    dest: '/opt/minecraft/server.properties'
    owner: 'minecraft'
    group: 'minecraft'
    mode: 0644
